# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Elena Vilimaite
description: >- # this means to ignore newlines until "baseurl:"
  London based innovative, confident and motivated software engineer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Sass_Jazz
github_username:  elena-vi

# Build settings
# theme: jekyll-theme-minimal
# theme: minima
plugins:
  - github-pages
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

remote_theme: jekyll/minima

locale: en_GB

author:
  name: Elena Vilimaite
  twitter: Sass_Jazz
  image: images/el_small.png
twitter:
  username: Sass_Jazz
  card: summary_large_image
social:
  name: Elena Vilimaite
  links:
    - https://twitter.com/Sass_Jazz
    - https://www.linkedin.com/in/elenavilimaite
    - https://github.com/elena-vi

minima:
  skin: auto

  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
  social_links:
    - { platform: github,         user_url: "https://github.com/elena-vi" }
    # - { platform: instagram,      user_url: "https://www.instagram.com/sass_jazz" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/elenavilimaite" }
    - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/4235396/elena" }
    # - { platform: twitter,        user_url: "https://twitter.com/Sass_Jazz" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up. 
#
# header_pages:
#   - about.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
